<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HR7OA0S" name="2.4.1.0 chunk2" tests="10" failures="1" timestamp="17 Feb 2016 15:14:59 GMT" time="29.216" errors="0">
  <testcase name="checkRetrieveMeasurementsUnits" time="1.19" classname="tests.TestRetrieveMeasurementsUnits"/>
  <testcase name="test_1670" time="20.605" classname="tests.TestRetrieveInvoiceInfo"/>
  <testcase name="test_1368" time="0.552" classname="tests.TestInvoiceHeaders"/>
  <testcase name="test_1413_1427" time="0.62" classname="tests.TestInvoiceHeaders"/>
  <testcase name="test_1492" time="26.105" classname="tests.TestRetrieveInvoiceInfo"/>
  <testcase name="test_1467" time="26.24" classname="tests.TestRetrieveInvoiceInfo"/>
  <testcase name="test_1432" time="0.418" classname="tests.TestInvoiceHeaders"/>
  <testcase name="test_1485" time="27.039" classname="tests.TestRetrieveInvoiceInfo"/>
  <testcase name="test_1463" time="27.648" classname="tests.TestRetrieveInvoiceInfo"/>
  <testcase name="test_1656" time="0.882" classname="tests.TestInvoiceHeaders">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at tests.TestInvoiceHeaders.test_1656(TestInvoiceHeaders.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_1656 -->
</testsuite> <!-- 2.4.1.0 chunk2 -->
