<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HR7OA0S" name="tests.TestInvoiceHeaders_NoInvoiceCreation" tests="13" failures="0" timestamp="22 Jan 2016 10:15:53 GMT" time="9.405" errors="1">
  <testcase name="test_1433" time="0.255" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1484" time="0.460" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1456_2" time="0.448" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1509" time="0.190" classname="tests.TestInvoiceHeaders_NoInvoiceCreation">
    <error type="org.testng.SkipException" message="Skipping Test: Test is skipped because there is no invoices with Cancelled status">
      <![CDATA[org.testng.SkipException: Skipping Test: Test is skipped because there is no invoices with Cancelled status
	at tests.TestInvoiceHeaders_NoInvoiceCreation.test_1509(TestInvoiceHeaders_NoInvoiceCreation.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- test_1509 -->
  <testcase name="test_1456_3" time="0.509" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1432" time="0.467" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1424" time="0.344" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1446" time="0.236" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1449" time="0.487" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1456" time="0.485" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1489" time="3.919" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1411" time="0.507" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
  <testcase name="test_1448_1436" time="1.098" classname="tests.TestInvoiceHeaders_NoInvoiceCreation"/>
</testsuite> <!-- tests.TestInvoiceHeaders_NoInvoiceCreation -->
