<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HR7OA0S" name="tests.TestExtInvSupPortal" tests="27" failures="2" timestamp="22 Jan 2016 10:15:53 GMT" time="144.608" errors="0">
  <testcase name="test_1408" time="36.822" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1339" time="6.006" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_1" time="4.346" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_8" time="4.079" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_9" time="4.117" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1479" time="2.042" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1483" time="3.797" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_14" time="3.743" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1466" time="3.463" classname="tests.TestExtInvSupPortal">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at tests.TestExtInvSupPortal.test_1466(TestExtInvSupPortal.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_1466 -->
  <testcase name="test_1442" time="0.986" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_11" time="3.929" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1498" time="3.347" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_13" time="3.735" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_7" time="4.356" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_3" time="5.826" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_10" time="3.532" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1455" time="4.496" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_5" time="4.561" classname="tests.TestExtInvSupPortal"/>
  <testcase name="testExternalInvoice" time="4.154" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_6" time="3.954" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1503" time="4.717" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1499" time="5.657" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_12" time="3.766" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1549" time="4.658" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_4" time="4.829" classname="tests.TestExtInvSupPortal"/>
  <testcase name="test_1506_2" time="4.973" classname="tests.TestExtInvSupPortal">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at tests.TestExtInvSupPortal.checkFileExtension(TestExtInvSupPortal.java:496)
	at tests.TestExtInvSupPortal.test_1506_2(TestExtInvSupPortal.java:530)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_1506_2 -->
  <testcase name="test_1458" time="4.717" classname="tests.TestExtInvSupPortal"/>
</testsuite> <!-- tests.TestExtInvSupPortal -->
